#! /usr/bin/env perl

use strict;

my $count = 0;

foreach ( 1 .. 2000 ) {
    $count += 1;

    my @s;
    my @q;

    foreach my $i ( 0 .. 99) {
        push @s, ('a', 'c', 'g', 't')[ rand(3.999999) ];
        push @q, chr( 65 + rand( 26 ));
    }

    my $s = join('', @s);
    my $q = join('', @q);

    print "\@MIKITA:$count:stan\n$s\n+extra_header_for:MIKITA:$count:stan\n$q\n";
}
