#! /usr/bin/env perl

use strict;

my $readlen = 50;

foreach ( 1 .. 20 ) {
    foreach my $i ( 1 .. 20 ) {
        my @c = split(//, chr( 64 + $i ) x $readlen);

        print "\@MIKITA:$i:stan\n";
        while (@c) {
            if (rand() < 0.1) {
                print "\n";
            }
            else {
                print shift(@c);
            }
        }
        print "\n";

        my @q = split(//, lc chr( 64 + $i ) x $readlen);

        print "+extra_header_for:MIKITA:$i:stan\n";
        while (@q) {
            if (rand() < 0.1) {
                print "\n";
            }
            else {
                print shift(@q);
            }
        }
        print "\n";
    }
}
